# Python NumPy Library for Data Analysis

In [ ]:
# install NumPy
# pip install numpy

### Creating NumPy Arrays

- Using Array Methods

In [ ]:
# The array() method is used to create a NumPy array
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)


numpy.ndarray

In [ ]:
# You can also create a multi-dimensional NumPy array
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape

(3, 3)

- Using Arrange Method

In [ ]:
#You can create an array that contains a range of integers using arrange () method.
nums_arr = np.arange(5,11)
print (nums_arr)


[ 5  6  7  8  9 10]


In [ ]:
# You can also specify the step as a third parameter in the arrange() function.
nums_arr = np.arange(5,12,2)
print (nums_arr)

[ 5  7  9 11]


- Using Ones Method


In [ ]:
# The ones() method can be used to create a NumPy array of all ones.
ones_array = np.ones(6)
print (ones_array)

[1. 1. 1. 1. 1. 1.]


In [ ]:
# You can create a 2-dimensional array with the one() method
ones_array = np.ones((6,4))
print (ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


- Using Zeros Method

In [ ]:
# The zeros() method can be used to create a NumPy array of all zeros.
zeros_array = np.zeros(6)
print (zeros_array)


[0. 0. 0. 0. 0. 0.]


In [ ]:
# You can create a 2-dimensional array with the zero() method
zeros_array = np.zeros((6,4))
print (zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- using Eyes Method

The eye() method is used to create an identity matrix in the form of a 2-dimensional
numPy array. An identity contains 1s along the diagonal, while the rest of the
elements are 0 in the array.

In [ ]:
eyes_array = np.eye(5)
print (eyes_array)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


- Using Random Method

In [ ]:
# The random.rand() function from the NumPy module can be used to create a
# NumPy array with uniform distribution.

uniform_random = np.random.rand(4, 5)
print (uniform_random)


[[0.97989933 0.06249651 0.52243182 0.47896403 0.9158505 ]
 [0.78514812 0.3890522  0.9655543  0.59429245 0.92181295]
 [0.31644162 0.085513   0.23798504 0.09274729 0.89498318]
 [0.02738916 0.95111112 0.36710897 0.82140217 0.92620781]]


In [ ]:
# The random.randn() function is used to create a random array with normal distribution
normal_random = np.random.randn(4, 5)
print (uniform_random)

[[0.97989933 0.06249651 0.52243182 0.47896403 0.9158505 ]
 [0.78514812 0.3890522  0.9655543  0.59429245 0.92181295]
 [0.31644162 0.085513   0.23798504 0.09274729 0.89498318]
 [0.02738916 0.95111112 0.36710897 0.82140217 0.92620781]]


In [ ]:
# random.randint() used to create an array with random integers between a certain range
integer_random = np.random.randint(10, 50, 5)
print (integer_random)


[10 17 20 36 45]


- Reshaping NumPy Arrays

In [ ]:
# An array can be reshaped using the reshape() function.
uniform_random = np.random.rand(4, 6)
uniform_random = uniform_random.reshape(3, 8)
print (uniform_random)


[[0.21905945 0.2574032  0.35071604 0.71416393 0.52307463 0.80958169
  0.77118422 0.5862466 ]
 [0.7297315  0.65073747 0.36013968 0.42421764 0.98678772 0.52116246
  0.14101133 0.69783402]
 [0.58586958 0.50300013 0.45121652 0.25284184 0.71047593 0.83322831
  0.83174998 0.9230083 ]]


- Array Indexing And Slicing

*Array indexing* is the same as accessing an array element.

*Slicing* in python means taking elements from one given index to another given index

In [ ]:
s = np.arange(1,11)
print (s)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# The item at index one can be accessed as follows:
print (s[1])


2


In [ ]:
# To slice an array, you have to pass the lower index, followed by a colon and the upper index.
print (s[1:9])


if you specify only the upper bound, all the items from the first index to the upper
bound are returned. similarly, if you specify only the lower bound, all the items
from the lower bound to the last item of the array are returned.

In [ ]:
print (s[:5])
print (s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
# Array slicing can also be applied on a 2-dimensional array
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print (nums_2d[:2,:])

[[10 12 13]
 [45 32 16]]


In [ ]:
# Similarly, the following script returns all the rows but only the first two columns.
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print (nums_2d[:,:2])


[[10 12]
 [45 32]
 [45 32]]


In [ ]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print (nums_2d[1:,1:])


[[32 16]
 [32 16]]


### NumPy for Arithmetic Operations

- Finding Square Roots

In [ ]:
# The sqrt() function is used to find the square roots
nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print (np_sqr)


[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


- Finding Logs

In [ ]:
# The log() function is used to find the logs
nums = [10,20,30,40,50]
np_log = np.log(nums)
print (np_log)


[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


- Finding Exponents

In [ ]:
# The exp() function takes the exponents
nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print (np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


- Finding Sine and Cosine


In [ ]:
# You can find the sines and cosines of items in a list using the sine and cosine function

nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print (np_sine)

nums = [10,20,30,40,50]
np_cos = np.cos(nums)
print (np_cos)


[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


### NumPy for Linear Algebra Operations


- Finding Matrix Dot Product

To find a matrix dot product, you can use the dot() function. 

In [ ]:
A = np.random.randn(4,5)

B = np.random.randn(5,4)

Z = np.dot(A,B)

print (Z)

[[-3.00202215 -8.41136155 -8.38590476  3.79425322]
 [ 0.40800158  3.20912312  4.00377694  0.03093067]
 [-5.40768873 -0.18611662 -2.39490983 -5.50429812]
 [-2.41531849 -1.84811838 -1.01339848 -1.23545497]]


- Element-wise Matrix Multiplication

In [ ]:
# you can element-wise multiply two matrices using multiply() function.
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
multiply = np.multiply(nums_2d, nums_2d)
print (multiply)


[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


- Finding Matrix Inverse

In [ ]:
# You find the inverse of a matrix via the linalg.inv() function
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])

inverse = np.linalg.inv(nums_2d)
print (inverse)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


# Finding Matrix Determinant


In [ ]:
# Similarly, the determinant of a matrix can be found using the linalg.det() function

row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]
nums_2d = np.array([row1, row2, row3])

determinant = np.linalg.det(nums_2d)
print (determinant)


-9.51619735392994e-16


- Finding Matrix Trace

In [ ]:
# The trace() function of a matrix refers to the sum of all the elements along the diagonal of a
matrix.
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])

trace = np.trace(nums_2d)
print (trace)

15
